#!/usr/bin/env python

import sys
import qrcode
from PIL import Image

if __name__ == "__main__":
    #img = qrcode.make('Hello, world\n')
    #img = qrcode.make('Hello, world\n', border=0)
    #img = qrcode.make('Hello, world\n', is_water=True, radius=10000)
    #img = qrcode.make('Hello, world\n', is_round=True, radius=10000)
    #img = qrcode.make('Hello, world\n', is_water=True, radius=10000, fore_color='purple', back_color='white')
    #img = qrcode.make('Hello, world\n', is_round=True, radius=10000, fore_color='purple', back_color='white')
    img = qrcode.make('Hello, worldsdfafsad;faskd;fjskdajfa;sjfsajf;asjfasjf;ajfsfsjfiuwerpuwruwqperwernweqnr;wenr;qwr;qwrkwqjr;qjrqjr\n', back_img='hybrid.jpg')
    #img = qrcode.make('Hello, world\n', back_img='000.jpg')
    img.save('out.png')
